apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ab3-ci
  region: ap-southeast-1
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 6
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: false
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        albIngress: true
        appMesh: true
        appMeshPreview: true
        autoScaler: true
        certManager: true
        cloudWatch: true
        ebs: true
        efs: true
        externalDNS: true
        xRay: true      
iam:
  withOIDC: true