############################################################
# Namespaces
############################################################
apiVersion: v1
kind: Namespace
metadata:
  name: ab3test
  labels:
    app: ab3test
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    mesh: ab3test-mesh
---
kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
