############################################################
# Namespace
############################################################
apiVersion: v1
kind: Namespace
metadata:
  name: ab3test
  labels:
    app: ab3test
#    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled


############################################################
# Logging
############################################################
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match   *
        region ap-southeast-1
        log_group_name fluent-bit-cloudwatch
        log_stream_prefix from-fluent-bit-
        auto_create_group On


############################################################
# Deployments
############################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab3test-deployment-jukebox-v1
  namespace: ab3test
  labels:
    app: ab3test
    service: jukebox
    version: 0.1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ab3test
  template:
    metadata:
      labels:
        app: ab3test
        service: jukebox
        version: 0.1.0
    spec:
      containers:
      - name: app
        image: 238435206887.dkr.ecr.ap-southeast-1.amazonaws.com/jukebox:0.1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab3test-deployment-rap-v1
  namespace: ab3test
  labels:
    app: ab3test
    service: rap
    version: 0.1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ab3test
  template:
    metadata:
      labels:
        app: ab3test
        service: rap
        version: 0.1.0
    spec:
      containers:
      - name: app
        image: 238435206887.dkr.ecr.ap-southeast-1.amazonaws.com/rap:0.1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab3test-deployment-rock-v1
  namespace: ab3test
  labels:
    app: ab3test
    service: rock
    version: 0.1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ab3test
  template:
    metadata:
      labels:
        app: ab3test
        service: rock
        version: 0.1.0
    spec:
      containers:
      - name: app
        image: 238435206887.dkr.ecr.ap-southeast-1.amazonaws.com/rock:0.1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi


############################################################
# Services
############################################################
---
apiVersion: v1
kind: Service
metadata:
  name: ab3test-service-jukebox-v1
  namespace: ab3test
  labels:
    app: ab3test
    service: jukebox
    version: 0.1.0
spec:
  type: NodePort
  selector:
    app: ab3test
    service: jukebox
    version: 0.1.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ab3test-service-rap-v1
  namespace: ab3test
  labels:
    app: ab3test
    service: rap
    version: 0.1.0
spec:
  type: NodePort
  selector:
    app: ab3test
    service: rap
    version: 0.1.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ab3test-service-rock-v1
  namespace: ab3test
  labels:
    app: ab3test
    service: rock
    version: 0.1.0
spec:
  type: NodePort
  selector:
    app: ab3test
    service: rock
    version: 0.1.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


############################################################
# Ingress
############################################################
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ab3test
  name: ab3test-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: ab3test
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ab3test-service-jukebox-v1
              servicePort: 80