apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab3test-deployment-a
  namespace: dev
  labels:
    app: ab3test
    service: a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ab3test
  template:
    metadata:
      labels:
        app: ab3test
        service: a
    spec:
      containers:
      - name: ab3test-service-a
        image: 238435206887.dkr.ecr.ap-southeast-1.amazonaws.com/service-a:0.1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ab3test-service-a
  namespace: dev
  labels:
    app: ab3test
spec:
  type: NodePort
  selector:
    app: ab3test
    service: a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab3test-deployment-b
  namespace: dev
  labels:
    app: ab3test
    service: b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ab3test
  template:
    metadata:
      labels:
        app: ab3test
        service: b
    spec:
      containers:
      - name: ab3test-service-b
        image: 238435206887.dkr.ecr.ap-southeast-1.amazonaws.com/service-b:0.1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ab3test-service-b
  namespace: dev
  labels:
    app: ab3test
spec:
  type: NodePort
  selector:
    app: ab3test
    service: b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab3test-deployment-c
  namespace: dev
  labels:
    app: ab3test
    service: c
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ab3test
  template:
    metadata:
      labels:
        app: ab3test
        service: c
    spec:
      containers:
      - name: ab3test-service-c
        image: 238435206887.dkr.ecr.ap-southeast-1.amazonaws.com/service-c:0.1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ab3test-service-c
  namespace: dev
  labels:
    app: ab3test
spec:
  type: NodePort
  selector:
    app: ab3test
    service: c
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000